### ISSUE TITLE
[Feature Request/Bug] Air Bubbles Restore in Spec

### ISSUE THREAD

**Issue by RillSoji** [CuzIm1Tigaaa/Spectator#10]
Currently the plugin allows the player to regain all air bubbles if they move out of the water while in spectate. Would like to see a fix or config option to retain the status of the player's air when switching in/out of spec. Thank you!

**Comment by Geckomacabre** [comment]
Tiga if you can try to contact RealBaconEater or https://github.com/cunhar for help developing this plugin. He has a Youtube called Hoobs Live that utilizes a plugin very similar to this.🙏

**Comment by CuzIm1Tigaaa** [comment]
> Currently the plugin allows the player to regain all air bubbles if they move out of the water while in spectate. Would like to see a fix or config option to retain the status of the player's air when switching in/out of spec. Thank you!

Sorry for the late response. I think the air should get restored even if the player does not leave the water in spectator mode, right? If so, of course I can add a config value for this.

**Comment by RillSoji** [comment]
No worries! It's just a semi-cheaty way to avoid drowning lol

**Comment by CuzIm1Tigaaa** [comment]
Yeah I know 😅
same with burning to death bc you stop burning after switching to spectator mode haha

**Comment by CuzIm1Tigaaa** [comment]
The remaing air and the fire ticks are now saved when going in spectator mode. This is configurable under "PlayerData", default is set to true.
If true, both the remaing air and the duration a player is burning are applied when leaving spectator mode
