### ISSUE TITLE
[Enhancement] Notify player if they being spectated

### ISSUE THREAD

**Issue by cupangafk** [CuzIm1Tigaaa/Spectator#12]
this can be an option in the config

and some bypass (with permission) for the spectating player

**Comment by CuzIm1Tigaaa** [comment]
Thanks for your Idea
I am currently on vacation and will have a look at this when I'm back!

**Comment by CuzIm1Tigaaa** [comment]
The feature has been added to the newest version of the plugin, available on spigotmc
