### ISSUE TITLE
[Bug] Cheating items with Multiverse

### ISSUE THREAD

**Issue by RillSoji** [CuzIm1Tigaaa/Spectator#17]
Bug/Problem: Players retain their creative world inventory when using /spec and moving through multiverse portals. 

Setup: 
Paper Version 1.20.1 #169 
Install Multiverse Core, Multiverse Portals, and Multiverse Inventories
Setup a survival world and a creative world where the player inventory and game mode swap appropriately for the world they are in. Create a multiverse portal to travel between the two worlds.

Reproduce Bug:
1. Walk into the creative world. Inventory swaps and game mode swaps as expected. 
2. Put creative menu items into inventory. 
3. Use /spec to enter spectator mode then float through the mv portal to the survival world. Player will remain in spec and inventory swaps as expected. 
4. Use /spec to return to the creative world. Player game mode returns to creative as expected. Player inventory disappears entirely.
5. Walk through the mv portal back to the survival world. Player game mode swaps as expected but player now has their inventory from the creative world. 

Testing:
- Setting all configs that have anything to do with inventory to false did not resolve the issue. Setting player data to false also did not resolve the issue. 
- Installing a diff spectator plugin does not reproduce the bug either. (I prefer not to use it since it's been abandoned by the developer and dropping errors in console but it was good enough to test for this purpose). 
- Disabling the Spectator plugin and testing the same process with manually setting gamemode doesn't reproduce the behavior. Inventory swaps correctly as expected. 

I'm not sure what is causing the issue but suspect it has something to do with the forced gamemode of the creative world and/or whatever Spectator is doing to track and store inventory information clashing with MV Inventories. 

I can provide a test environment if needed, just let me know!

**Comment by CuzIm1Tigaaa** [comment]
Hey,

thank you for your bug report! I'll try to fix this asap.

**Comment by CuzIm1Tigaaa** [comment]
So... currently I could fix it so that players in spectator mode cannot duplicate items any more.
BUT that only works when the spectating player is not spectating any player... have to look for a solution for this, but I'm clueless... otherwise I have to disable world switching as spectator completely (maybe only for Multiverse worlds, because Nether/End of same world with same Inventory would also be affected)

**Comment by TylorTurner** [comment]
Hopefully this gets fixed soon.

**Comment by CuzIm1Tigaaa** [comment]
After a lot of testing and figuring out, how to fix this problem, it finally seems to work.
I really hope that this problem is fixed in the upcoming update.

Tested for spectators without target, spectators spectating players and also speccycle.

I am sorry that this took some time.

**Comment by TylorTurner** [comment]
Heck yeah! I have been dealing with this for at least 6 months! Thank you so much.
