### ISSUE TITLE
[Bug] SpecCycle delete inventory if player is already in default spec

### ISSUE THREAD

**Issue by RillSoji** [CuzIm1Tigaaa/Spectator#19]
If a player has used /gamemode spectator or F3+F4 to swap gamemodes the vanilla/OP way and then uses /speccycle it will delete their inventory.

**Comment by CuzIm1Tigaaa** [comment]
Hi,
I am very sorry that this took so long. As tested right now, this issue should be fixed in the upcoming update.

Best regards
