### ISSUE TITLE
[Feature Request] add PlaceholderAPI support for message

### ISSUE THREAD

**Issue by cupang-afk** [CuzIm1Tigaaa/Spectator#23]
especially for message that display player name :)

**Comment by CuzIm1Tigaaa** [comment]
PlaceholderAPI has been added to the plugin. Every chat message should now support placeholders.
Also there are a few custom placeholders from the plugin itself, they can be viewed [Here](https://github.com/CuzIm1Tigaaa/Spectator/wiki/Placeholders)
