### ISSUE TITLE
Spectating different dimensions is broken & getting stuck in spec mode leading to inventory loss

### ISSUE THREAD

**Issue by ArionOwO** [CuzIm1Tigaaa/Spectator#28]
1. Players who aren't OPs and have the permissions to spectate players when attempting to spectate other players in a different dimention than they are currently in will fall through the world and die and sometimes lose their inventories. 

2. Also my mods will sometimes get stuck in spec mode and when i manually change their gamemode back to survival because they're stuck in spec mode they'll lose their inventories, I have yet to expereince this myself I believe because i'm an OP it doesn't happen to me but i'll keep looking into what's causing the issue. Also my server is 1.20.4 and always on the latest build of paper.

**Comment by CuzIm1Tigaaa** [comment]
Hey,

I could not reproduce the first issue. I was not in OP and I tried switching between Nether/End/Overworld with another account and then spectating this one. Could you maybe provide more information?

About the other issue: I am trying to rewrite the whole inventory saving process of the plugin. But I'm afraid that this could take a while.

**Comment by ArionOwO** [comment]
The spectating a player in a different dimention isn't occuring anymore on current latest version of paper build#423, I don't remember which specific build I was using pror but it was over 15 builds ago so it shouldn't be an issue anymore, as for the mods getting stuck in spec mode I haven't seen is since either but that issue occured randomly not everytime like the other issue so i'll let you know if that issue is still occuring.
