### ISSUE TITLE
Specycle doesn't work when only OP'd players are online

### ISSUE THREAD

**Issue by MCHalfAssed** [CuzIm1Tigaaa/Spectator#29]
Currently using Paper 1.20.4, Spectator v2.3.

If you try to start a specycle with only OP players online, it automatically pauses/stops the cycle and never starts. de-op'ing one of the two players allows specycle to work normally again. 

If it helps, my suggestion would be to add an option in the config to allow OP players to be spectated or not.

**Comment by MCHalfAssed** [comment]
Also, turning the player's OP back on stops the cycle

**Comment by CuzIm1Tigaaa** [comment]
There is a permission, which should normally do the trick.
Setting spectator.bypass.spectated to **false** should work.

**Comment by CuzIm1Tigaaa** [comment]
Since there's no answer, I assume the problem has been solved
