### ISSUE TITLE
Getting out of date error

### ISSUE THREAD

**Issue by Geckomacabre** [CuzIm1Tigaaa/Spectator#3]
is it possible to update the plugin for 1.19?

**Comment by Tvhee-Dev** [comment]
Hello,

I have decided to comply with your request. I have opened a pull request too: https://github.com/CuzIm1Tigaaa/Spectator/pull/4. I have attached the jar file for you.

[Spectator.zip](https://github.com/CuzIm1Tigaaa/Spectator/files/9148733/Spectator.zip)

If you have any questions, you can reach out to me via Discord: Tvhee#4828.

Regards,
Tvhee

**Comment by CuzIm1Tigaaa** [comment]
Fixed with the latest version.
