### ISSUE TITLE
Bug Spectating /Spawn Command

### ISSUE THREAD

**Issue by TylorTurner** [CuzIm1Tigaaa/Spectator#31]
Spectate Player (zSpec1)
Enter Portal to another world (Multiverse Portals)
Player uses TP command or forced

Spectator Bugged while spectating
https://streamable.com/qdn32k

**Comment by CuzIm1Tigaaa** [comment]
Not sure if I understand this issue.
Seems to be similar to #32

**Comment by CuzIm1Tigaaa** [comment]
This issue could not be reproduced on my local server.

If this persists, please create a new report, where the server version, minecraft version and a list of plugins is given.
