### ISSUE TITLE
[Issue] Speccycle; Chunks are not loaded for spectating player

### ISSUE THREAD

**Issue by TylorTurner** [CuzIm1Tigaaa/Spectator#32]
/Speccycle start anytime

speccycle does not work at all and give weird glitch screens player to player.

1.20.4 

https://streamable.com/ttpnwf

**Comment by CuzIm1Tigaaa** [comment]
My guess is, that the problems origin is from minecraft or spigot/paper (chunks are not loaded for spectator)

Otherwise the speccycle seems to work fine...

**Comment by TylorTurner** [comment]
How can I fix speccyle in that case?

**Comment by CuzIm1Tigaaa** [comment]
As I said, it is just my guess. I will try to find a solution but I cannot promise anything

**Comment by DaddyRobLIVE** [comment]
please update, this is also happening to me :/

**Comment by CuzIm1Tigaaa** [comment]
This issue could not be reproduced on my local server.

If this persists, please create a new report, where the server version, minecraft version and a list of plugins is given.
