### ISSUE TITLE
[Issue] Target World switching deletes spectators inventory

### ISSUE THREAD

**Issue by TylorTurner** [CuzIm1Tigaaa/Spectator#34]
Spectate player (Zspec2) in world with same inventory (Multiverse Inventories)
Players (Zspec2) walks in to world with different inventory. 
Spectator loses inventory and turns in to survival.

https://streamable.com/kza5pl

**Comment by MeteoraCD2** [comment]
Regardless of installed plugins, inventory may disappear
I noticed only one pattern: moving to nether or end

**Comment by CuzIm1Tigaaa** [comment]
Is your nether / end accessable through multiverse?
Because I tested it and the inv is looking fine for me.

It disappears when switching between other multiverse worlds though...

**Comment by TylorTurner** [comment]
Any world that isn't the sams inventory. So typically end and Nether would
be fine.
