### ISSUE TITLE
The ability to switch the visibility of invisible armorstands

### ISSUE THREAD

**Issue by Vinellon** [CuzIm1Tigaaa/Spectator#36]
I would like to see a function so that invisible armor stands can be hidden so that they do not interfere with the view.
![изображение](https://github.com/CuzIm1Tigaaa/Spectator/assets/96441768/8a6af6dc-78a4-409d-8006-a2859ce39c42)

**Comment by CuzIm1Tigaaa** [comment]
You want invisible armor stands to be invisible to spectating players, right?
Or am I misunderstanding?

**Comment by Vinellon** [comment]
> You want invisible armor stands to be invisible to spectating players, right? Or am I misunderstanding?

yep

**Comment by CuzIm1Tigaaa** [comment]
I am very sorry for the late response. I was not able to fix any issues on this plugin lately.

This feature is now added. There is a config value (Settings.HideArmorStands) that has to be enabled. And with /spec -armorstand you can toggle the visiblity of armorstands for spectators (includes hidden and non-hidden ones)

Thank you for your patience.
