### ISSUE TITLE
Player is not starting a spec cycle

### ISSUE THREAD

**Issue by Geckomacabre** [CuzIm1Tigaaa/Spectator#5]
When using the new updated to the plugin my player remains " Searching for next Target " and does not find any player.

**Comment by CuzIm1Tigaaa** [comment]
Is there any error message?
How many players were online?
Did you try to restart the cycle (Also with a different interval)?

**Comment by Geckomacabre** [comment]
> Is there any error message? How many players were online? Did you try to restart the cycle (Also with a different interval)?
No there is no log errors, when trying i had 5 players online including the spec account, and yes ive tried many different times to restart the cycle, i even added the specific permissions to my account.

**Comment by JonDeschenes** [comment]
Same for me, i'm stuck on "Searching next Target..."

**Comment by CuzIm1Tigaaa** [comment]
I'll fix this / have a look at this issue when I'm back at home!
Also I'm cleaning up the current code.

**Comment by CuzIm1Tigaaa** [comment]
Found my mistake! I'm sorry...
This is fixed in the next version 😊
